### ISSUE TITLE
Error `Malformed version number string loading ~/.bashrc`

### ISSUE THREAD

**Issue by ironsand** [matschaffer/knife-solo#410]
I have functions that are defined dynamically in `~/.bashrc` in server like:

```bash
for func in guard rspec rake cap; do
        eval "
        ${func}() {
                local foo=(command ${func})
                [ -e 'Gemfile' ] && foo=(bundle exec ${func})
                \"\${foo[@]}\" \"\$@\"
        }
        "
done
```

Then `knife solo cook foo` ends up with error like:

```
ERROR: ArgumentError: Malformed version number string loading ~/.bashrc                                 
guard is a function                                                                                     
guard ()                                                                                                
{                                                                                                       
    local foo=(command guard);                                                                          
    [ -e 'Gemfile' ] && foo=(bundle exec guard);                                                        
    "${foo[@]}" "$@"                                                                                    
}                                                                                                       
rspec is a function                                                                                     
rspec ()                                                                                                
{                                                                                                       
    local foo=(command rspec);                                                                          
    [ -e 'Gemfile' ] && foo=(bundle exec rspec);                                                        
    "${foo[@]}" "$@"                                                                                    
}                                                                                                       
rake is a function                                                                                      
rake ()                                                                                                 
{                                                                                                       
    local foo=(command rake);                                                                           
    [ -e 'Gemfile' ] && foo=(bundle exec rake);                                                         
    "${foo[@]}" "$@"                                                                                    
}                                                                                                       
11.8.2                                                                                                  
```

I'll handle it by removing these lines in `.bashrc` this time, but I'd be delighted if the error is removed in future version.

Thanks.

**Comment by ironsand** [comment]
I closed this issue because I couldn't reproduce the error, but I found what is happening. So I reopen this issue.

It appears `check_chef_version` method expects Chef's version, instead of that the method receives `~/.bashrc` output. That was the cause of error.

This is my `~/.bashrc`

```
echo "loading ~/.bashrc"
```

And this is the whole error message.

```
$ knife solo cook ubuntu -VV
Starting 'Run'
Running Chef on ubuntu...
Checking Chef version...
DEBUG: Initial command sudo chef-solo --version 2>/dev/null | awk '$1 == "Chef:" {print $2}'
DEBUG: Initial command sudo -V
DEBUG: Running processed command sudo -V
DEBUG: sudo -V stdout: loading ~/.bashrc
Sudo version 1.8.9p5
DEBUG: sudo -V stdout:

DEBUG: sudo -V stdout: Sudoers policy plugin version 1.8.9p5
DEBUG: sudo -V stdout:

DEBUG: sudo -V stdout: Sudoers file grammar version 43
DEBUG: sudo -V stdout:

DEBUG: sudo -V stdout: Sudoers I/O plugin version 1.8.9p5
DEBUG: sudo -V stdout:

DEBUG: Running processed command sudo -E -p 'knife sudo password: ' chef-solo --version 2>/dev/null | awk '$1 == "Chef:" {print $2}'
DEBUG: sudo -E -p 'knife sudo password: ' chef-solo --version 2>/dev/null | awk '$1 == "Chef:" {print $2}' stdout: loading ~/.bashrc

DEBUG: sudo -E -p 'knife sudo password: ' chef-solo --version 2>/dev/null | awk '$1 == "Chef:" {print $2}' stdout: 11.8.2
DEBUG: sudo -E -p 'knife sudo password: ' chef-solo --version 2>/dev/null | awk '$1 == "Chef:" {print $2}' stdout:

C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:206:in `initialize': Malformed version number string loading ~
 (ArgumentError)
11.8.2
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:198:in `new'
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:198:in `new'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:286:in `chef_version_satisfies
?'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:277:in `check_chef_version'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:86:in `block in run'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:208:in `time'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:75:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:44:in `load'
        from C:/opscode/chefdk/bin/knife:44:in `<main>'
```

What should I to circumvent this error?


Best Regards

**Comment by matschaffer** [comment]
I think the options might be to remove the echo from `.bashrc`. You could also try using `--startup-script` to point to a file that doesn't echo but I suspect `.bashrc` will still get loaded in addition to the specified startup script.

**Comment by ironsand** [comment]
Thanks for your reply!

I'll use `--no-chef-check` option from now on.

Best Regards.
