### ISSUE TITLE
knife solo cook fails often in Windows when using cygwin's rsync

### ISSUE THREAD

**Issue by ironsand** [matschaffer/knife-solo#420]
When I run `knife solo cook ubuntu` in Windows, I works fine once every two or three times.
But sometimes I get the following error:

```
Uploading the kitchen...
ERROR: RuntimeError: Failed to launch command ["rsync", "-rL", "--chmod=ugo=rwX", "--rsh=ssh vagrant@ubuntu", "--delete-after", "--exclude=revision-deploys", "--exclude=tmp", "--exclude=.git", "--exclude=.hg", "--exclude=.svn", "--exclude=.bzr", "/cygdrive/C/Users/ironsand/dev/chef-trusty-ironsand/cookbooks/", ":~/chef-solo/cookbooks-3"]
```

By rewriting code, it found out the command fails with error code `100`. But `rsync` ends successfully with return code `0`.

```
diff -Nur a/knife-solo-0.4.2/lib/knife-solo/tools.rb b/knife-solo-0.4.2/lib/knife-solo/tools.rb
--- a/knife-solo-0.4.2/lib/knife-solo/tools.rb  2014-06-06 16:13:54.000000000 +0900
+++ b/knife-solo-0.4.2/lib/knife-solo/tools.rb  2015-01-13 13:53:14.000000000 +0900
@@ -1,7 +1,16 @@
 module KnifeSolo
   module Tools
     def system!(*command)
-      raise "Failed to launch command #{command}" unless system(*command)
+      if command[0] == 'rsync'
+        system(*command)
+        status = $?.exitstatus
+        if status != 0 && status != 24
+          raise "Failed to launch command (#{status}) #{command}"
+        end
+        
+      else                    
+        raise "Failed to launch command #{command}" unless system(*command)
+      end 
     end

     def windows_client?
```

```
diff -Nur a/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb b/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb
--- a/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb  2014-06-06 16:13:54.000000000 +0900
+++ b/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb  2015-01-13 14:11:31.000000000 +0900
@@ -184,7 +184,7 @@
       end

       def rsync_debug
-        '-v' if debug?
+        '-vvv' if debug?
       end

       # see http://stackoverflow.com/questions/5798807/rsync-permission-denied-created-directories-have-no-permissions
```

After the code change the error message became like this:

```
generate_files phase=3
generate_files finished

sent 184 bytes  received 847 bytes  687.33 bytes/sec
total size is 811  speedup is 0.79
[sender] _exit_cleanup(code=0, file=main.c, line=1183): about to call exit(0)
C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/knife-solo/tools.rb:10:in `system!': Failed to launch command (100) ["rsync", "-rL", "-vvv", "--chmod=ugo=rwX", "--rsh=ssh vagrant@ubuntu", "--delete-after", "--exclude=revision-deploys", "--exclude=tmp", "--exclude=.git", "--exclude=.hg", "--exclude=.svn", "--exclude=.bzr", "/cygdrive/C/Users/ironsand/AppData/Local/Temp/solo.rb20150115-1272-134yk99", ":~/chef-solo/solo.rb"] (RuntimeError)
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:273:in `rsync'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:230:in `upload'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:255:in `write'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:226:in `generate_solorb'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:93:in `block in run'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:209:in `time'
        from C:/Users/ironsand/.chefdk/gem/ruby/2.0.0/gems/knife-solo-0.4.2/lib/chef/knife/solo_cook.rb:75:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:44:in `load'
        from C:/opscode/chefdk/bin/knife:44:in `<main>'
```

This error happens only when I'm using cygwin's `rsync`, After switching to `cwRsync` the problem disappeared.

We have talked about it in Japanese Stackoverflow.
http://ja.stackoverflow.com/questions/2441/knife-solo-%E3%81%A7-rsync%E3%81%8Cfailed-to-launch-command%E3%81%A7%E9%A0%BB%E7%B9%81%E3%81%AB%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B

Personally I'll stick to use `cwRsync`, so for me it doesn't problem anymore.
I just hope, someone who have the same problem find the solution more easily.

Best Regards.

**Comment by matschaffer** [comment]
Very odd. Will close this out then since it doesn't look like we need to change anything in knife-solo. Thanks for the report!

**Comment by matschaffer** [comment]
I also put a [comment](https://ja.stackoverflow.com/questions/2441/knife-solo-%E3%81%A7-rsync%E3%81%8Cfailed-to-launch-command%E3%81%A7%E9%A0%BB%E7%B9%81%E3%81%AB%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B?newreg=608110a9b5f44e07abae0ee783895932#comment3290_4478) on the accepted answer. The error condition is interesting and especially interesting is how it ends up masked as a 100. Yay computers :)

**Comment by paul42** [comment]
I'm sorry to bring this back up, but I can't quite follow how the fix was done - where was cygwin's rsync switched to cwRsync? I'm getting the same error and I can't quite follow how this was fixed.

Thanks in advance,

**Comment by ironsand** [comment]
I renamed cygwin's rsync so that to make `cwRsync` only rsync command available. (Probably set proper PATH is enough, I just wanted to be sure.)

But after I switched `cwRsync` there were errors sometimes, and I didn't want to struggle with it.
Therefore I patch the code that accept `100` is ok.

```
diff -Nur a/knife-solo-0.4.2/lib/knife-solo/tools.rb b/knife-solo-0.4.2/lib/knife-solo/tools.rb
--- a/knife-solo-0.4.2/lib/knife-solo/tools.rb  2014-06-06 16:13:54.000000000 +0900
+++ b/knife-solo-0.4.2/lib/knife-solo/tools.rb  2015-01-13 13:53:14.000000000 +0900
@@ -1,7 +1,16 @@
 module KnifeSolo
   module Tools
     def system!(*command)
-      raise "Failed to launch command #{command}" unless system(*command)
+      if command[0] == 'rsync'
+        system(*command)
+        status = $?.exitstatus
+        if status != 0 && status != 24 && status != 100
+          raise "Failed to launch command (#{status}) #{command}"
+        end
+        
+      else                    
+        raise "Failed to launch command #{command}" unless system(*command)
+      end 
     end
```

**Comment by matschaffer** [comment]
Interesting. @ironsand I'd be willing to have that as a patch if you want to submit it. I'd really like to get off rsync at some point (probably adopt knife-zero's approach) but can't say when I'll have the bandwidth.
