### ISSUE TITLE
Gem::ConflictError net-ssh-4.1.0

### ISSUE THREAD

**Issue by matejvelikonja** [matschaffer/knife-solo#513]
Since upgrading to the latest chefDK, I've started receiving this error on latest MacOS. Does anyone knows what could be the problem?

```bash
$ knife solo -v
/opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate knife-solo-0.6.0, because net-ssh-4.1.0 conflicts with net-ssh (< 4.0, >= 2.7) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/user/.chefdk/gem/ruby/2.3.0/gems/knife-solo-0.6.0/lib/chef/knife/cook.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:100:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:100:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:100:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:100:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:110:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/core/subcommand_loader.rb:124:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:57:in `load'
	from /opt/chefdk/bin/knife:57:in `<main>'
```

```bash
chef -v                                                                                                     
Chef Development Kit Version: 1.5.0
chef-client version: 12.21.2
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```

**Comment by matschaffer** [comment]
I'd install the 0.7.0 pre-release. That should have compatible gem requirements.

**Comment by matejvelikonja** [comment]
@matschaffer you are right `chef gem install knife-solo -v 0.7.0.pre` did the trick.
